<?php
$string = "Hello\tThere";
$string = "Hello There\r\n";
$string = "Hello There";
$string = "Hello $there";
$string = 'Hello'."$there '".'hi';
$string = "My name is 'Greg'";
$string = "Hello"." There"."\n";
$string = "Hello There\f";
$string = "Hello\vThere";
$string = "\x0";
$string = 'Hello '.$there.' Greg';
$string = "<div class='$class'>";
$string = "Value: $var[test]";
$string = "\0";

$x = "bar = '$z',
baz = '" . $a . "'...$x";
?>