<?php
if ($something) {
}
foreach ($this as $that) {
}
while (true) {
    for ($i = 0; $i < 10; $i++) {
    }
    if ($something) {
    }

    foreach ($this as $that) {
        do {
        } while (true) {
        }
    }
}

if ($one) {
} else ($two) {
} else if ($three) {
} elseif ($four) {
}
if ($one) {
} else ($two) {
} else if ($three) {
} elseif ($four) {
}
?>
<table>
    <tr>
        <td align="center" valign="center">
        <?php
        foreach ($this->children as $child) {
            // There should be no error after this
            // foreach, because it is followed by a
            // close PHP tag.
        }
        ?>
        </td>
    </tr>
</table>
<?php
?>