
<?php
echo 'hi';
echo 'hello';   
    
if ($something) {  
    
}


function myFunction()
{
    echo 'code here';

    echo 'code here';


    // Hello.

    /*
        HI
    */


}
// @codingStandardsChangeSetting Squiz.WhiteSpace.SuperfluousWhitespace ignoreMultipleBlanklines true
function myFunction2()
{
    echo 'code here';


    echo 'code here';

}
// @codingStandardsChangeSetting Squiz.WhiteSpace.SuperfluousWhitespace ignoreMultipleBlanklines false
// @codingStandardsChangeSetting Squiz.WhiteSpace.SuperfluousWhitespace ignoreWhitespaceOnBlankLines true

function myFunction2()
{
    echo 'code here';
    
    echo 'code here';
    
}

// @codingStandardsChangeSetting Squiz.WhiteSpace.SuperfluousWhitespace ignoreWhitespaceOnBlankLines false

?>

