
<?php
echo 'hi';
echo 'hello';   
    
if ($something) {  
    
}


function myFunction()
{
    echo 'code here';

    echo 'code here';


    // Hello.

    /*
        HI
    */


}

function myFunction2()
{
    echo 'code here';


    echo 'code here';

}

// @codingStandardsChangeSetting Squiz.WhiteSpace.SuperfluousWhitespace ignoreBlankLines true

function myFunction2()
{
    echo 'code here';
    
    echo 'code here';
    
}

// @codingStandardsChangeSetting Squiz.WhiteSpace.SuperfluousWhitespace ignoreBlankLines false

?>

