<?php
// This is a normal block comment that might
// talk about functions like echo and print and if/else but
// is not commented out code.

// if (empty($this)) {echo 'This is will not work';}

/*
function myFunction()
{

}//end myFunction()
*/

//eval('$var = 4;');
//$string = '$var = 4;';
//eval($string);

#eval('$var = 4;');
#$string = '$var = 4;';
#eval($string);

if ($blah) {
    // This is a multi-line comment that goes over two indented
    // lines.

    // If it's null, then there must be no parameters for this
    // method.
}

// short.

// Continue, as we're done with this token.

/**
 * The listeners array.
 *
 * @var array(PHP_CodeSniffer_Sniff)
 */

//

/*
*/

function myFunction()
{
}//end myFunction()

// ----------------------------
// | A comment block           |
// ----------------------------

// =============================
// | A comment block           |
// =============================

// *****************************
// | A comment block           |
// *****************************
?>
