<?php
    // Not embedded. Do not check here.
    echo 'hello';
?>
<html>
<head>
<title><?php echo $title ?></title>
<script><?php echo $script; ?></script>
</head>
<body>
    <?php
        echo $body;
    ?>
    hello
    <?php
    echo $moreBody;
    ?>
    <?php  echo 'hi'; ?>
    <?php  echo 'hi';   ?>
    <?php echo 'hi;' ?>
    <?php echo 'hi'; echo 'hi;'; ?>
    <?php  echo 'hi'; echo 'hi;';   ?>

    <?php
    ?>
    <?php ?>

    <?php

        echo $moreBody;

    ?>
    <?php

    echo $moreBody;

    ?>

    <?php
    echo $moreBody; ?>
    <?php echo $moreBody;
    ?>
</body>
</html>
<?php
// Not embedded. Do not check here.
echo 'goodbye';
?>
