<?php

function test()
{
    // Body here.
}

function test()
{
    echo 'foo';}

function test()
{
    // Body here.

}

function test()
{
    // Body here.


}

class MyClass
{
    function test()
    {
        // Body here.
    }

    function test()
    {
        echo 'foo';}

    function test()
    {
        // Body here.

    }

    function test()
    {
        // Body here.


    }
}

$foo = function test()
{
    // Body here.
};

$foo = function test()
{
     echo 'foo';};

$foo = function test()
{
    // Body here.

};

$foo = function test()
{
    // Body here.


};
