<?php
/**
 * FIXME: really need to fix this before I commit.
 *
 */

// FIXME: this is broken, don't forget to fix it
error_log('test');

// FIXME remove this.
Debug::bam('test');

// fixme - fix this.

// Extract info from the array.
// FIXME: this is just a stub, fill in later

// Extract info from the array (fixme: finish later)
// To do this, use a function!
// nofixme! NOFIXME! NOfixme!
//FIXME.
//éfixme
//fixmeé
