<?php
/**
 * TODO: Write this comment
 *
 */

// TODO: remove this.
error_log('test');

// TODO remove this.
Debug::bam('test');

// todo - remove this.

// Extract info from the array.
// TODO: can this be done faster?

// Extract info from the array (todo: make it faster)
// To do this, use a function!
// notodo! NOTODO! NOtodo!
//TODO.

/**
 * FIXME: really need to fix this before I commit.
 *
 */

// FIXME: this is broken, don't forget to fix it
error_log('test');

// FIXME remove this.
Debug::bam('test');

// fixme - fix this.

// Extract info from the array.
// FIXME: this is just a stub, fill in later

// Extract info from the array (fixme: finish later)
// To do this, use a function!
// nofixme! NOFIXME! NOfixme!
//FIXME.

?>
