<?php

foreach ($array as $for => $value);
foreach ($array as $value);
foreach ($array as $value);;
foreach ($array as $value)
;
foreach ($array as $value)
{};
foreach ($array as $value)
;
{};

foreach ($array as $for => $value){
}
foreach ($array as $for => $value){}
foreach ($array as $for => $value) // with comment
{}
foreach ($array as $for => $value)
{};

for (;;);
for ($i =0; $i<10; $i++);
for ($i =0;; $i++);
for ($i =0;; $i++)
    ;
for ($i =0;; $i++) {} ;
for ($i =0;; $i++); {} ;
for ($i =0;; $i++) //with comment
;