<?php
// A few keywords. Obviously not valid syntax.
class Something extends SomethingElse implements Whatever
abstract public private protected function whatever() {}
const array()
for ($var as $var) { exit; }
if ($a and $b or $c xor $d) { die; } elseif { } else
goto a;

Class Something EXTENDS SomethingElse implementS Whatever
Abstract Public Private Protected function whatever() {}
CONST array()
For ($var As $var) { Exit; }
If ($a AND $b OR $c XOR $d) { Die; } ElseIf { } Else
GOTO a;
function (Array $a) {}
const PRIVATE;
HttpStatus::CONTINUE;
function
