<?php
$GLOBALS['TSFE']->additionalHeaderData[$this->strApplicationName]
     = $this->xajax->getJavascript(t3lib_extMgm::siteRelPath('nr_xajax'));

$GLOBALS['TSFE']->additionalHeaderData[$this->strApplicationName]
   = $this->xajax->getJavascript(t3lib_extMgm::siteRelPath('nr_xajax'));

$GLOBALS['TSFE']->additionalHeaderData[$this->strApplicationName] = 
    $this->xajax->getJavascript(t3lib_extMgm::siteRelPath('nr_xajax'));

$GLOBALS['TSFE']->additionalHeaderData[$this->strApplicationName]
    = $this->xajax->getJavascript(t3lib_extMgm::siteRelPath('nr_xajax'));
$GLOBALS['TSFE']->additionalHeaderData[$this->strApplicationName] = 'boo';

$var='string';

function getInstalledStandards(
    $includeGeneric=false,
    $standardsDir=''
) {
}
?>
