<?php

class ExampleClass
{
    function exampleFunction() {}

}

    $o = <<<EOF
    this is some text
    this is some text
EOF;

	$correctVar = false;
    $correctVar = true;

// Indent with spaces is not allowed
 $hello = array();
   $world = '';
// here the indention is mixed with tabs and spaces
// [tab][space][space][space][tab]return "<$name$xmlns$type_str $atts xsi:nil=\"true\"/>";
	   	return "<$name$xmlns$type_str $atts xsi:nil=\"true\"/>";
// [space][space][space][tab]return "<$name$xmlns$type_str $atts xsi:nil=\"true\"/>";
   	return "<$name$xmlns$type_str $atts xsi:nil=\"true\"/>";
// Doc comments are indent with tabs and one space
//[tab]/**
//[tab][space]*
	/**
	 * CVS revision for HTTP headers.
     *
	  * @var string
	 * @access private
	 */
	/**
     *
	*/
