<?php

function MyFunction1()
{
    // Some code goes here.
    echo $code;
}

function MyFunction2()
{

    // Some code goes here.
    echo $code;
}

class MyClass
{
    function MyFunction1()
    {
        // Some code goes here.
        echo $code;
    }

    function MyFunction2()
    {

        // Some code goes here.
        echo $code;
    }

    public function register();
}

class MyClass1
{

    public function foo()
    {
    }
}

interface MyInterface
{

    public function foo();
}

trait MyTrait
{

    public function foo()
    {
    }
}

enum MyEnum
{

    case Foo;
}

function emptyFunction()
{

}//end emptyFunction();

public function register();

function allOnOneLine() { echo 'abc'; }

$a = function()
{
	echo 'Testing a closure';
};

$a = function()
{



	echo 'Testing a closure';
};
