<?php

function MyFunction1() {
    // Some code goes here.

}

function MyFunction2() {
    // Some code goes here.
}

class MyClass
{
    function MyFunction3() {
        // Some code goes here.

    }

    function MyFunction4() {
        // Some code goes here.
    }

    public function register();
}

public function register();

function foo() { }
function foo() {}
function foo() {
}

function foo()
{
    for ($i = 0; $i < $bar; $i++) {
    }//end for


}
