<?php
$this->testThis();
$this-> testThis();
$this    ->  testThis();
$this->/* comment here */testThis();
$this/* comment here */ -> testThis();
$this
    ->testThis();
$this->
    testThis();

// @codingStandardsChangeSetting Squiz.WhiteSpace.ObjectOperatorSpacing ignoreNewlines true

$this->testThis();
$this-> testThis();
$this    ->  testThis();
$this->/* comment here */testThis();
$this/* comment here */ -> testThis();
$this
    ->testThis();
$this->
    testThis();

// @codingStandardsChangeSetting Squiz.WhiteSpace.ObjectOperatorSpacing ignoreNewlines false
