<?php
/**
 * Short content.
 *
 * @return void
 *
 * @api           read
 * @api-privilege asset.read.content
 * @api-mustlock  false
 */
private function functionCall() {}

/**
 * Short content.
 *
 * @return void
 *
 * @api read
 */
private function functionCall() {}

/**
 * Short content.
 *
 * @api read
 *
 * @return void
 */
private function functionCall() {}

/**
 * Short content.
 *
 * @return void
 *
 * @api-privilege asset.read.content
 * @api           read
 * @api-mustlock  false
 */
private function functionCall() {}

/**
 * Short content.
 *
 * @return void
 *
 * @api           read
 *
 * @api-privilege asset.read.content
 * @api-mustlock  false
 */
private function functionCall() {}

/**
 * Short content.
 *
 * @return void
 * @api read
 */
private function functionCall() {}

/**
 * Test unknown tags.
 *
 * @return  void
 * @since   read
 * @hello   hello
 * @package Test
 */
private function functionCall() {}

/**
 * Short content.
 *
 * @return void
 *
 * @api read
 * @api-privilege asset.read.content
 * @api-mustlock false
 */
private function functionCall() {}

/**
 * Short content.
 *
 * @return void
 *
 * @api          read
 * @api-mustlock false
 */
private function functionCall() {}

/**
 * Short content.
 *
 * @return void
 *
 * @api read
 */
private function functionCall() {}
?>
