<?php
/**
 * Short description.
 *
 * Long description
 * over multiple lines.
 *
 * @tag1 one
 * @tag2 two
 * @tag3 three
 */

/**
 * short description
 *
 * long description
 * over multiple lines.
 * @tag1 one
 */

/**
 *
 * Short description
 *
 *
 * Long description
 * over multiple lines
 *
 *
 * @tag1 one
 *
 */

/*
    This is not a doc block.
 */

/** Short description.
 *
 * @tag one
 * @tag2 two
 * @tagThree three
 * @tagFour  four
 */