<?php
/**
 * Some info about the class here
 *
 */
class MyClass
{
    /**
     * Some info about the function here.
     *
     *@return void
     */
    function myFunction() {}
}

/**
  *  Some info about the class here
  *
  */
class MyClass
{
    /**
      *Some info about the function here.
      *
      *  @return void
      */
    function myFunction() {}
}

/**
 * Some info about the class here
  *
*/
class MyClass
{
    /**
     * Some info about the function here.
      *
    * @return void
     */
    function myFunction() {}
}

?>